/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Java.Apartamento;
import Java.Despesa;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.SpinnerListModel;

/**
 *
 * @author Houdini
 */
public class Adicionar_Despesas extends javax.swing.JFrame {

    private Apartamento apartamento;
    private String username;
    /**
     * Creates new form Adicionar_Despesas
     */
    public Adicionar_Despesas(Apartamento a, String username) {
        initComponents();
        this.apartamento = a;
        this.username = username;
        setSpinners();
    }
    
    private void setSpinners() {
        SpinnerListModel tl;
        List<String> l = new ArrayList<>();
        List<String> t = new ArrayList<>();
        t.add("Recorrente");
        t.add("Extraordinária");
        
        tl = new SpinnerListModel(t);
        jSpinnerTipo.setModel(tl);
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxBanco = new javax.swing.JCheckBox();
        jCheckBoxDinheiro = new javax.swing.JCheckBox();
        jCheckBoxTrans = new javax.swing.JCheckBox();
        jSpinnerTipo = new javax.swing.JSpinner();
        jSpinnerLimite = new javax.swing.JSpinner();
        jTextFieldQuantia = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldReferencia = new javax.swing.JTextField();
        jLabelAdicionar = new javax.swing.JLabel();
        jLabelButtonHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDataLimite = new javax.swing.JLabel();
        jLabelQuantia = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jCheckBoxBanco.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jCheckBoxBanco.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxBanco.setText("MultiBanco");
        getContentPane().add(jCheckBoxBanco);
        jCheckBoxBanco.setBounds(540, 230, 111, 29);

        jCheckBoxDinheiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jCheckBoxDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxDinheiro.setText("Dinheiro");
        getContentPane().add(jCheckBoxDinheiro);
        jCheckBoxDinheiro.setBounds(540, 270, 110, 29);

        jCheckBoxTrans.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCheckBoxTrans.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTrans.setText("Tranferência");
        getContentPane().add(jCheckBoxTrans);
        jCheckBoxTrans.setBounds(540, 310, 110, 30);

        jSpinnerTipo.setModel(new javax.swing.SpinnerListModel(new String[] {""}));
        getContentPane().add(jSpinnerTipo);
        jSpinnerTipo.setBounds(190, 230, 150, 30);

        jSpinnerLimite.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jSpinnerLimite.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(jSpinnerLimite);
        jSpinnerLimite.setBounds(190, 410, 150, 30);
        getContentPane().add(jTextFieldQuantia);
        jTextFieldQuantia.setBounds(190, 350, 150, 30);
        getContentPane().add(jTextFieldCategoria);
        jTextFieldCategoria.setBounds(190, 290, 150, 30);
        getContentPane().add(jTextFieldReferencia);
        jTextFieldReferencia.setBounds(500, 430, 200, 30);

        jLabelAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar2.png"))); // NOI18N
        jLabelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAdicionar);
        jLabelAdicionar.setBounds(220, 480, 110, 40);

        jLabelButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"))); // NOI18N
        jLabelButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonHome);
        jLabelButtonHome.setBounds(20, 470, 80, 80);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("procedimento do pagamento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 380, 214, 21);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduza os dados para o");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 360, 200, 21);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Método de Pagamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 140, 270, 40);

        jLabelDataLimite.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelDataLimite.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataLimite.setText("Data Limite");
        getContentPane().add(jLabelDataLimite);
        jLabelDataLimite.setBounds(80, 410, 90, 30);

        jLabelQuantia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelQuantia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantia.setText("Quantia");
        getContentPane().add(jLabelQuantia);
        jLabelQuantia.setBounds(110, 350, 70, 30);

        jLabelCategoria.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setText("Categoria");
        getContentPane().add(jLabelCategoria);
        jLabelCategoria.setBounds(100, 290, 80, 30);

        jLabelTipo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Tipo de Despesa");
        getContentPane().add(jLabelTipo);
        jLabelTipo.setBounds(50, 230, 130, 30);

        jLabelAdd.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setText("Adicionar Despesa");
        getContentPane().add(jLabelAdd);
        jLabelAdd.setBounds(60, 150, 240, 30);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SignUp_screen.jpg"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 790, 560);

        setSize(new java.awt.Dimension(806, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseEntered

    private void jLabelButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseExited

    private void jLabelButtonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_pressed.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMousePressed

    private void jLabelButtonHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseReleased

    private void jLabelButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseClicked
        close();
        Menu_Inicial s = new Menu_Inicial(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelButtonHomeMouseClicked

    private void jLabelAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar2_over.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseEntered

    private void jLabelAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar2.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseExited

    private void jLabelAdicionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar2_pressed.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMousePressed

    private void jLabelAdicionarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar2_over.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseReleased

    private void jLabelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseClicked
        String t = (String) jSpinnerTipo.getValue();
        String categoria = (String) jTextFieldCategoria.getText();
        float custo = Float.parseFloat(jTextFieldQuantia.getText());
        Date data_limite = (Date) jSpinnerLimite.getValue();
        int referencia = -1;
        int id_despesa = apartamento.getListaTotal().size();
        
        boolean tipo;
        tipo = t.equals("Recorrente");
        
        if(!jCheckBoxDinheiro.isSelected()){
            referencia = Integer.parseInt(jTextFieldReferencia.getText());
        }
        Despesa d = new Despesa(custo, data_limite, tipo, categoria, false, referencia, id_despesa);
        apartamento.adicionarDespesa(d);
        close();
        Menu_Inicial s = new Menu_Inicial(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelAdicionarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxBanco;
    private javax.swing.JCheckBox jCheckBoxDinheiro;
    private javax.swing.JCheckBox jCheckBoxTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAdicionar;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelButtonHome;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDataLimite;
    private javax.swing.JLabel jLabelQuantia;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JSpinner jSpinnerLimite;
    private javax.swing.JSpinner jSpinnerTipo;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldQuantia;
    private javax.swing.JTextField jTextFieldReferencia;
    // End of variables declaration//GEN-END:variables
}
