/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Houdini
 */
public class CriarMorador extends javax.swing.JFrame {

    /**
     * Creates new form CriarMorador
     */
    public CriarMorador() {
        initComponents();
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jSpinnerSaida = new javax.swing.JSpinner();
        jSpinnerEntrada = new javax.swing.JSpinner();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelButtonHome = new javax.swing.JLabel();
        jLabelCriar = new javax.swing.JLabel();
        jLabelDataSaida = new javax.swing.JLabel();
        jLabelDataEntrada = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelREgist = new javax.swing.JLabel();
        jLabelBackGRound = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jSpinnerSaida.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jSpinnerSaida.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(jSpinnerSaida);
        jSpinnerSaida.setBounds(260, 400, 160, 30);

        jSpinnerEntrada.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jSpinnerEntrada.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(jSpinnerEntrada);
        jSpinnerEntrada.setBounds(260, 340, 160, 30);

        jTextFieldNome.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(260, 220, 190, 30);

        jTextFieldMail.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldMail);
        jTextFieldMail.setBounds(260, 280, 190, 30);

        jLabelButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"))); // NOI18N
        jLabelButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonHomeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonHome);
        jLabelButtonHome.setBounds(690, 470, 80, 80);

        jLabelCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonCriar.png"))); // NOI18N
        jLabelCriar.setText("jLabel1");
        jLabelCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCriarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCriarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCriarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCriarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCriarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelCriar);
        jLabelCriar.setBounds(290, 460, 85, 40);

        jLabelDataSaida.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelDataSaida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataSaida.setText("Data de Saída");
        getContentPane().add(jLabelDataSaida);
        jLabelDataSaida.setBounds(130, 400, 130, 30);

        jLabelDataEntrada.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelDataEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataEntrada.setText("Data de Entrada");
        getContentPane().add(jLabelDataEntrada);
        jLabelDataEntrada.setBounds(120, 340, 140, 30);

        jLabelMail.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMail.setText("E-mail");
        getContentPane().add(jLabelMail);
        jLabelMail.setBounds(190, 280, 70, 30);

        jLabelNome.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome ");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(190, 220, 70, 30);

        jLabelREgist.setFont(new java.awt.Font("Cooper Black", 0, 30)); // NOI18N
        jLabelREgist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelREgist.setText("Regista-te");
        getContentPane().add(jLabelREgist);
        jLabelREgist.setBounds(50, 140, 160, 35);

        jLabelBackGRound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SignUp_screen.jpg"))); // NOI18N
        jLabelBackGRound.setText("jLabel1");
        getContentPane().add(jLabelBackGRound);
        jLabelBackGRound.setBounds(0, 0, 790, 559);

        setSize(new java.awt.Dimension(807, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCriarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_over.png"));
        jLabelCriar.setIcon(II);
    }//GEN-LAST:event_jLabelCriarMouseEntered

    private void jLabelCriarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar.png"));
        jLabelCriar.setIcon(II);
    }//GEN-LAST:event_jLabelCriarMouseExited

    private void jLabelCriarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_pressed.png"));
        jLabelCriar.setIcon(II);
    }//GEN-LAST:event_jLabelCriarMousePressed

    private void jLabelCriarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_over.png"));
        jLabelCriar.setIcon(II);
    }//GEN-LAST:event_jLabelCriarMouseReleased

    private void jLabelCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarMouseClicked
        close();
        Morador s = null;
        try {
            s = new Morador();
        } catch (SQLException ex) {
            Logger.getLogger(CriarMorador.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.add(this.jTextFieldNome.getText());
        jTextFieldNome.setText("");
        s.setVisible(true);
    }//GEN-LAST:event_jLabelCriarMouseClicked

    private void jLabelButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseEntered

    private void jLabelButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseExited

    private void jLabelButtonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_pressed.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMousePressed

    private void jLabelButtonHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelButtonHome.setIcon(II);
    }//GEN-LAST:event_jLabelButtonHomeMouseReleased

    private void jLabelButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonHomeMouseClicked
        close();
        Morador s = null;
        try {
            s = new Morador();
        } catch (SQLException ex) {
            Logger.getLogger(CriarMorador.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setVisible(true);
    }//GEN-LAST:event_jLabelButtonHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CriarMorador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackGRound;
    private javax.swing.JLabel jLabelButtonHome;
    private javax.swing.JLabel jLabelCriar;
    private javax.swing.JLabel jLabelDataEntrada;
    private javax.swing.JLabel jLabelDataSaida;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelREgist;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner jSpinnerEntrada;
    private javax.swing.JSpinner jSpinnerSaida;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
