/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Java.Apartamento;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Houdini
 */
public class Despesas extends javax.swing.JFrame {

    private Apartamento apartamento;
    private String username;
    /**
     * Creates new form Despesas
     */
    public Despesas(Apartamento a, String username) {
        initComponents();
        this.apartamento = a;
        this.username = username;
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExtraordinarias = new javax.swing.JLabel();
        jLabelRecorrentes = new javax.swing.JLabel();
        jLabelAdicionar = new javax.swing.JLabel();
        jLabelPagamento = new javax.swing.JLabel();
        jLabelDespesas = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelExtraordinarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonExtraordinarias.png"))); // NOI18N
        jLabelExtraordinarias.setText("jLabel2");
        jLabelExtraordinarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExtraordinariasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExtraordinariasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExtraordinariasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelExtraordinariasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelExtraordinariasMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelExtraordinarias);
        jLabelExtraordinarias.setBounds(320, 290, 110, 40);

        jLabelRecorrentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonRecorrentes.png"))); // NOI18N
        jLabelRecorrentes.setText("jLabel2");
        jLabelRecorrentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRecorrentesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRecorrentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRecorrentesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRecorrentesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRecorrentesMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelRecorrentes);
        jLabelRecorrentes.setBounds(320, 220, 110, 40);

        jLabelAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar.png"))); // NOI18N
        jLabelAdicionar.setText("jLabel2");
        jLabelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAdicionarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAdicionar);
        jLabelAdicionar.setBounds(320, 360, 110, 40);

        jLabelPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonPagamento.png"))); // NOI18N
        jLabelPagamento.setText("jLabel2");
        jLabelPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPagamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPagamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPagamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelPagamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPagamentoMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPagamento);
        jLabelPagamento.setBounds(320, 430, 110, 40);

        jLabelDespesas.setFont(new java.awt.Font("Cooper Black", 0, 30)); // NOI18N
        jLabelDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDespesas.setText("Despesas");
        getContentPane().add(jLabelDespesas);
        jLabelDespesas.setBounds(310, 130, 140, 50);

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"))); // NOI18N
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelHome);
        jLabelHome.setBounds(20, 470, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SignUp_screen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 560);

        setSize(new java.awt.Dimension(807, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRecorrentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecorrentesMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonRecorrentes_over.png"));
        jLabelRecorrentes.setIcon(II);
    }//GEN-LAST:event_jLabelRecorrentesMouseEntered

    private void jLabelRecorrentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecorrentesMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonRecorrentes.png"));
        jLabelRecorrentes.setIcon(II);
    }//GEN-LAST:event_jLabelRecorrentesMouseExited

    private void jLabelRecorrentesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecorrentesMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonRecorrentes_pressed.png"));
        jLabelRecorrentes.setIcon(II);
    }//GEN-LAST:event_jLabelRecorrentesMousePressed

    private void jLabelRecorrentesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecorrentesMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonRecorrentes_over.png"));
        jLabelRecorrentes.setIcon(II);
    }//GEN-LAST:event_jLabelRecorrentesMouseReleased

    private void jLabelExtraordinariasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExtraordinariasMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonExtraordinarias_over.png"));
        jLabelExtraordinarias.setIcon(II);
    }//GEN-LAST:event_jLabelExtraordinariasMouseEntered

    private void jLabelExtraordinariasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExtraordinariasMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonExtraordinarias.png"));
        jLabelExtraordinarias.setIcon(II);
    }//GEN-LAST:event_jLabelExtraordinariasMouseExited

    private void jLabelExtraordinariasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExtraordinariasMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonExtraordinarias_pressed.png"));
        jLabelExtraordinarias.setIcon(II);
    }//GEN-LAST:event_jLabelExtraordinariasMousePressed

    private void jLabelExtraordinariasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExtraordinariasMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonExtraordinarias_over.png"));
        jLabelExtraordinarias.setIcon(II);
    }//GEN-LAST:event_jLabelExtraordinariasMouseReleased

    private void jLabelAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar_over.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseEntered

    private void jLabelAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseExited

    private void jLabelAdicionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar_pressed.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMousePressed

    private void jLabelAdicionarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAdicionar_over.png"));
        jLabelAdicionar.setIcon(II);
    }//GEN-LAST:event_jLabelAdicionarMouseReleased

    private void jLabelPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagamentoMouseClicked
        close();
        Efetuar_Pagamento s = new Efetuar_Pagamento(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelPagamentoMouseClicked

    private void jLabelPagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagamentoMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPagamento_over.png"));
        jLabelPagamento.setIcon(II);
    }//GEN-LAST:event_jLabelPagamentoMouseEntered

    private void jLabelPagamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagamentoMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPagamento.png"));
        jLabelPagamento.setIcon(II);
    }//GEN-LAST:event_jLabelPagamentoMouseExited

    private void jLabelPagamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagamentoMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPagamento_pressed.png"));
        jLabelPagamento.setIcon(II);
    }//GEN-LAST:event_jLabelPagamentoMousePressed

    private void jLabelPagamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagamentoMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPagamento_over.png"));
        jLabelPagamento.setIcon(II);
    }//GEN-LAST:event_jLabelPagamentoMouseReleased

    private void jLabelRecorrentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecorrentesMouseClicked
        close();
        Recorrentes s = new Recorrentes(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelRecorrentesMouseClicked

    private void jLabelExtraordinariasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExtraordinariasMouseClicked
        close();
        Extraordinarias s = new Extraordinarias(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelExtraordinariasMouseClicked

    private void jLabelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionarMouseClicked
        close();
        Adicionar_Despesas s = new Adicionar_Despesas(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelAdicionarMouseClicked

    private void jLabelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseEntered

    private void jLabelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseExited

    private void jLabelHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_pressed.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMousePressed

    private void jLabelHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseReleased

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        close();
        Menu_Inicial s = new Menu_Inicial(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelHomeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdicionar;
    private javax.swing.JLabel jLabelDespesas;
    private javax.swing.JLabel jLabelExtraordinarias;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelPagamento;
    private javax.swing.JLabel jLabelRecorrentes;
    // End of variables declaration//GEN-END:variables
}
