/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Java.Apartamento;
import Java.Morador;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Houdini
 */
public class Escolhe_Morador extends javax.swing.JFrame {

    
        private Apartamento apartamento;
    /**
     * Creates new form Morador
     * @throws java.sql.SQLException
     */
    //MODEL
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultListModel dm = new DefaultListModel();
    
    public Escolhe_Morador(Apartamento a) throws SQLException{
        initComponents();
        this.apartamento = a;
        updateList();
        //FillListBox();
    }
    
    private void updateList(){
        DefaultListModel<String> l = new DefaultListModel<String>();
        try{
            for(Morador a : apartamento.getListaMoradores().values()){
                l.addElement(a.getUsername());
            }
        }
        catch (Exception e){
        
        }
        jListMorador.setModel((ListModel)l);
    }
    /*private void FillListBox() throws SQLException {
        try{
            String sql = "select * from morador";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            
            while(rs.next()) {
                String name = rs.getString("username");
                dm.addElement(name);
            }
            
            jListMorador.setModel(dm);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    
    public void add(String name) {
        jListMorador.setModel(dm);
        dm.addElement(name);
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /*public void populateJList(JList jListMorador, String query, Connection connection) throws SQLException
{
    DefaultListModel dm = new DefaultListModel(); //create a new list model

    Statement statement = connection.createStatement();
    ResultSet resultSet = statement.executeQuery(query); //run your query

    while (resultSet.next()) //go through each row that your query returns
    {
        String itemCode = resultSet.getString("nome"); //get the element in column "item_code"
        dm.addElement(itemCode); //add each item to the model
    }
    jListMorador.setModel(dm);

    resultSet.close();
    statement.close();

}*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListMorador = new javax.swing.JList<>();
        jLabelButtonEntrar = new javax.swing.JLabel();
        jLabelMorador = new javax.swing.JLabel();
        jLabelButtonCriar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jListMorador.setBackground(java.awt.SystemColor.activeCaption);
        jListMorador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jListMorador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListMorador);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 350, 140, 130);

        jLabelButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonEntrar.png"))); // NOI18N
        jLabelButtonEntrar.setText("jLabel2");
        jLabelButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonEntrar);
        jLabelButtonEntrar.setBounds(480, 370, 85, 40);

        jLabelMorador.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabelMorador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMorador.setText("Escolha um morador");
        getContentPane().add(jLabelMorador);
        jLabelMorador.setBounds(310, 310, 200, 30);

        jLabelButtonCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonCriar.png"))); // NOI18N
        jLabelButtonCriar.setText("jLabel2");
        jLabelButtonCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCriarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCriarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCriarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonCriarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonCriarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonCriar);
        jLabelButtonCriar.setBounds(480, 430, 85, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login_screen2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 794, 559);

        setSize(new java.awt.Dimension(808, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonEntrar_over.png"));
        jLabelButtonEntrar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonEntrarMouseEntered

    private void jLabelButtonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonEntrar.png"));
        jLabelButtonEntrar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonEntrarMouseExited

    private void jLabelButtonEntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonEntrar_pressed.png"));
        jLabelButtonEntrar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonEntrarMousePressed

    private void jLabelButtonEntrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonEntrar_over.png"));
        jLabelButtonEntrar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonEntrarMouseReleased

    private void jLabelButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseClicked
        String username = jListMorador.getSelectedValue();
        close();
        Menu_Inicial s = new Menu_Inicial(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelButtonEntrarMouseClicked

    private void jLabelButtonCriarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCriarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_over.png"));
        jLabelButtonCriar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonCriarMouseEntered

    private void jLabelButtonCriarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCriarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar.png"));
        jLabelButtonCriar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonCriarMouseExited

    private void jLabelButtonCriarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCriarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_pressed.png"));
        jLabelButtonCriar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonCriarMousePressed

    private void jLabelButtonCriarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCriarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonCriar_over.png"));
        jLabelButtonCriar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonCriarMouseReleased

    private void jLabelButtonCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCriarMouseClicked
        close();
        CriarMorador s = new CriarMorador(apartamento);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelButtonCriarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButtonCriar;
    private javax.swing.JLabel jLabelButtonEntrar;
    private javax.swing.JLabel jLabelMorador;
    public static javax.swing.JList<String> jListMorador;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
