/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss;

import javax.swing.ImageIcon;

/**
 *
 * @author Houdini
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Project
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelButtonLogin = new javax.swing.JLabel();
        jLabelButtonSair = new javax.swing.JLabel();
        jLabelSignUp = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelUsername.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username");
        getContentPane().add(jLabelUsername);
        jLabelUsername.setBounds(220, 330, 90, 30);

        jLabelPassword.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(220, 380, 70, 30);

        jLabelButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonLogin.png"))); // NOI18N
        jLabelButtonLogin.setText("jLabel1");
        jLabelButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonLogin);
        jLabelButtonLogin.setBounds(330, 420, 85, 40);

        jLabelButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonSair.png"))); // NOI18N
        jLabelButtonSair.setText("jLabel1");
        jLabelButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonSairMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonSairMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonSairMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonSair);
        jLabelButtonSair.setBounds(440, 420, 85, 40);

        jLabelSignUp.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabelSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSignUp.setText("Não tens conta? Inscreve-te já!");
        getContentPane().add(jLabelSignUp);
        jLabelSignUp.setBounds(330, 470, 190, 14);
        getContentPane().add(jTextFieldUsername);
        jTextFieldUsername.setBounds(310, 330, 230, 30);
        getContentPane().add(jPassword);
        jPassword.setBounds(310, 380, 230, 30);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login_screen2.jpg"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 790, 560);

        setSize(new java.awt.Dimension(807, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonLogin_over.png"));
        jLabelButtonLogin.setIcon(II);
    }//GEN-LAST:event_jLabelButtonLoginMouseEntered

    private void jLabelButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonLogin.png"));
        jLabelButtonLogin.setIcon(II);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonLoginMouseExited

    private void jLabelButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMouseClicked

    }//GEN-LAST:event_jLabelButtonLoginMouseClicked

    private void jLabelButtonLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonLogin_pressed.png"));
        jLabelButtonLogin.setIcon(II);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonLoginMousePressed

    private void jLabelButtonLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonLogin_over.png"));
        jLabelButtonLogin.setIcon(II);
    }//GEN-LAST:event_jLabelButtonLoginMouseReleased

    private void jLabelButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonSairMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonSair_over.png"));
        jLabelButtonSair.setIcon(II);
    }//GEN-LAST:event_jLabelButtonSairMouseEntered

    private void jLabelButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonSairMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonSair.png"));
        jLabelButtonSair.setIcon(II);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonSairMouseExited

    private void jLabelButtonSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonSairMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonSair_pressed.png"));
        jLabelButtonSair.setIcon(II);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonSairMousePressed

    private void jLabelButtonSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonSairMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonSair_over.png"));
        jLabelButtonSair.setIcon(II);
    }//GEN-LAST:event_jLabelButtonSairMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelButtonLogin;
    private javax.swing.JLabel jLabelButtonSair;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
