/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Java.Apartamento;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Houdini
 */
public class Menu_Inicial extends javax.swing.JFrame {
    
    private Apartamento apartamento;
    private String username;

    /**
     * Creates new form Menu_Inicial
     */
    public Menu_Inicial(Apartamento a, String username) {
        initComponents();
        this.apartamento = a;
        this.username = username;
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDespesas = new javax.swing.JLabel();
        jLabelApartamento = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelButtonVoltar = new javax.swing.JLabel();
        jLabelBemVindo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonDespesas.png"))); // NOI18N
        jLabelDespesas.setText("jLabel3");
        jLabelDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDespesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDespesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDespesasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDespesasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelDespesasMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelDespesas);
        jLabelDespesas.setBounds(350, 360, 110, 40);

        jLabelApartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonApartamento.png"))); // NOI18N
        jLabelApartamento.setText("jLabel2");
        jLabelApartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelApartamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelApartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelApartamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelApartamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelApartamentoMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelApartamento);
        jLabelApartamento.setBounds(350, 300, 110, 40);

        jLabelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonPerfil.png"))); // NOI18N
        jLabelPerfil.setText("jLabel1");
        jLabelPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPerfilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelPerfilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPerfilMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPerfil);
        jLabelPerfil.setBounds(350, 240, 110, 40);

        jLabelButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonVoltar.png"))); // NOI18N
        jLabelButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonVoltarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelButtonVoltarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonVoltarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelButtonVoltar);
        jLabelButtonVoltar.setBounds(20, 500, 85, 40);

        jLabelBemVindo.setFont(new java.awt.Font("Cooper Black", 0, 30)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBemVindo.setText("Bem vindo !");
        getContentPane().add(jLabelBemVindo);
        jLabelBemVindo.setBounds(320, 130, 190, 35);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SignUp_screen.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 792, 559);

        setSize(new java.awt.Dimension(808, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonVoltarMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonVoltar_over.png"));
        jLabelButtonVoltar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonVoltarMouseEntered

    private void jLabelButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonVoltarMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonVoltar.png"));
        jLabelButtonVoltar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonVoltarMouseExited

    private void jLabelButtonVoltarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonVoltarMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonVoltar_pressed.png"));
        jLabelButtonVoltar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonVoltarMousePressed

    private void jLabelButtonVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonVoltarMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonVoltar_over.png"));
        jLabelButtonVoltar.setIcon(II);
    }//GEN-LAST:event_jLabelButtonVoltarMouseReleased

    private void jLabelButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonVoltarMouseClicked
        close();
        Escolhe_Morador s = null;
        try {
            s = new Escolhe_Morador(apartamento);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setVisible(true);
    }//GEN-LAST:event_jLabelButtonVoltarMouseClicked

    private void jLabelPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfilMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPerfil_over.png"));
        jLabelPerfil.setIcon(II);
    }//GEN-LAST:event_jLabelPerfilMouseEntered

    private void jLabelPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfilMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPerfil.png"));
        jLabelPerfil.setIcon(II);
    }//GEN-LAST:event_jLabelPerfilMouseExited

    private void jLabelPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfilMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPerfil_pressed.png"));
        jLabelPerfil.setIcon(II);
    }//GEN-LAST:event_jLabelPerfilMousePressed

    private void jLabelPerfilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfilMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonPerfil_over.png"));
        jLabelPerfil.setIcon(II);
    }//GEN-LAST:event_jLabelPerfilMouseReleased

    private void jLabelApartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApartamentoMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonApartamento_over.png"));
        jLabelApartamento.setIcon(II);
    }//GEN-LAST:event_jLabelApartamentoMouseEntered

    private void jLabelApartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApartamentoMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonApartamento.png"));
        jLabelApartamento.setIcon(II);
    }//GEN-LAST:event_jLabelApartamentoMouseExited

    private void jLabelApartamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApartamentoMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonApartamento_pressed.png"));
        jLabelApartamento.setIcon(II);
    }//GEN-LAST:event_jLabelApartamentoMousePressed

    private void jLabelApartamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApartamentoMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonApartamento_over.png"));
        jLabelApartamento.setIcon(II);
    }//GEN-LAST:event_jLabelApartamentoMouseReleased

    private void jLabelDespesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDespesasMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonDespesas_over.png"));
        jLabelDespesas.setIcon(II);
    }//GEN-LAST:event_jLabelDespesasMouseEntered

    private void jLabelDespesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDespesasMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonDespesas.png"));
        jLabelDespesas.setIcon(II);
    }//GEN-LAST:event_jLabelDespesasMouseExited

    private void jLabelDespesasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDespesasMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonDespesas_pressed.png"));
        jLabelDespesas.setIcon(II);
    }//GEN-LAST:event_jLabelDespesasMousePressed

    private void jLabelDespesasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDespesasMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonDespesas_over.png"));
        jLabelDespesas.setIcon(II);
    }//GEN-LAST:event_jLabelDespesasMouseReleased

    private void jLabelDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDespesasMouseClicked
        close();
        Despesas s = new Despesas(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelDespesasMouseClicked

    private void jLabelPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfilMouseClicked
        close();
        Perfil s = new Perfil(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelPerfilMouseClicked

    private void jLabelApartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApartamentoMouseClicked
        close();
        Frame.Apartamento s = new Frame.Apartamento(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelApartamentoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelApartamento;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelButtonVoltar;
    private javax.swing.JLabel jLabelDespesas;
    private javax.swing.JLabel jLabelPerfil;
    // End of variables declaration//GEN-END:variables
}
