/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Java.Apartamento;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Houdini
 */
public class Perfil extends javax.swing.JFrame {

    private Apartamento apartamento;
    private String username;
    /**
     * Creates new form Perfil
     */
    public Perfil(Apartamento a, String username) {
        initComponents();
        this.apartamento = a;
        this.username = username;
        AddCont();
    }
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public void AddCont() {
        String mail = apartamento.getListaMoradores().get(username).getEmail();
        Date entrada = apartamento.getListaMoradores().get(username).getEntrada();
        Date saida = apartamento.getListaMoradores().get(username).getSaida();
        Float conta = apartamento.getListaMoradores().get(username).getConta();
        
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        
        jLabelNome2.setText(this.username);
        jLabelMail2.setText(mail);
        jLabelEntrada2.setText(df.format(entrada));
        jLabelSaida2.setText(df.format(saida));
        jLabelPagar2.setText(Float.toString(conta) + " €");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPath = new javax.swing.JTextField();
        jLabelPagar2 = new javax.swing.JLabel();
        jLabelMail2 = new javax.swing.JLabel();
        jLabelSaida2 = new javax.swing.JLabel();
        jLabelEntrada2 = new javax.swing.JLabel();
        jLabelNome2 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelShopIcon = new javax.swing.JLabel();
        jLabelPagar1 = new javax.swing.JLabel();
        jLabelMail1 = new javax.swing.JLabel();
        jLabelSaida1 = new javax.swing.JLabel();
        jLabelEntrada1 = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelAbrir = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldPath);
        jTextFieldPath.setBounds(40, 450, 210, 40);

        jLabelPagar2.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabelPagar2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelPagar2);
        jLabelPagar2.setBounds(630, 190, 120, 30);

        jLabelMail2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelMail2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelMail2);
        jLabelMail2.setBounds(410, 380, 330, 30);

        jLabelSaida2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelSaida2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelSaida2);
        jLabelSaida2.setBounds(490, 340, 260, 30);

        jLabelEntrada2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelEntrada2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelEntrada2);
        jLabelEntrada2.setBounds(510, 300, 230, 30);

        jLabelNome2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelNome2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelNome2);
        jLabelNome2.setBounds(410, 260, 300, 30);

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"))); // NOI18N
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelHome);
        jLabelHome.setBounds(680, 460, 80, 80);

        jLabelShopIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/shopping-cart.png"))); // NOI18N
        getContentPane().add(jLabelShopIcon);
        jLabelShopIcon.setBounds(490, 120, 70, 70);

        jLabelPagar1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelPagar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagar1.setText("Por pagar:");
        getContentPane().add(jLabelPagar1);
        jLabelPagar1.setBounds(570, 120, 150, 70);

        jLabelMail1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelMail1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMail1.setText("E-mail:");
        getContentPane().add(jLabelMail1);
        jLabelMail1.setBounds(330, 380, 70, 30);

        jLabelSaida1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelSaida1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaida1.setText("Data de Saída:");
        getContentPane().add(jLabelSaida1);
        jLabelSaida1.setBounds(330, 340, 150, 30);

        jLabelEntrada1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelEntrada1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEntrada1.setText("Data de entrada:");
        getContentPane().add(jLabelEntrada1);
        jLabelEntrada1.setBounds(330, 300, 170, 30);

        jLabelNome1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelNome1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome1.setText("Nome:");
        getContentPane().add(jLabelNome1);
        jLabelNome1.setBounds(330, 260, 70, 30);

        jLabelPerfil.setFont(new java.awt.Font("Cooper Black", 0, 30)); // NOI18N
        jLabelPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfil.setText("O meu perfil");
        getContentPane().add(jLabelPerfil);
        jLabelPerfil.setBounds(40, 120, 200, 50);

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/profile.png"))); // NOI18N
        getContentPane().add(jLabelImagem);
        jLabelImagem.setBounds(40, 200, 260, 230);

        jLabelAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonAbrir.png"))); // NOI18N
        jLabelAbrir.setText("jLabel2");
        jLabelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAbrirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAbrirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAbrirMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAbrir);
        jLabelAbrir.setBounds(260, 450, 85, 40);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SignUp_screen.jpg"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 780, 560);

        setSize(new java.awt.Dimension(796, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbrirMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAbrir_over.png"));
        jLabelAbrir.setIcon(II);
    }//GEN-LAST:event_jLabelAbrirMouseEntered

    private void jLabelAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbrirMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAbrir.png"));
        jLabelAbrir.setIcon(II);
    }//GEN-LAST:event_jLabelAbrirMouseExited

    private void jLabelAbrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbrirMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAbrir_pressed.png"));
        jLabelAbrir.setIcon(II);
    }//GEN-LAST:event_jLabelAbrirMousePressed

    private void jLabelAbrirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbrirMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonAbrir_over.png"));
        jLabelAbrir.setIcon(II);
    }//GEN-LAST:event_jLabelAbrirMouseReleased

    private void jLabelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbrirMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextFieldPath.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        jLabelImagem.setIcon(icon);
    }//GEN-LAST:event_jLabelAbrirMouseClicked

    private void jLabelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseEntered

    private void jLabelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseExited

    private void jLabelHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_pressed.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMousePressed

    private void jLabelHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Imagens/ButtonHome_over.png"));
        jLabelHome.setIcon(II);
    }//GEN-LAST:event_jLabelHomeMouseReleased

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        close();
        Menu_Inicial s = new Menu_Inicial(apartamento, username);
        s.setVisible(true);
    }//GEN-LAST:event_jLabelHomeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbrir;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelEntrada1;
    private javax.swing.JLabel jLabelEntrada2;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelMail1;
    private javax.swing.JLabel jLabelMail2;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelPagar1;
    private javax.swing.JLabel jLabelPagar2;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JLabel jLabelSaida1;
    private javax.swing.JLabel jLabelSaida2;
    private javax.swing.JLabel jLabelShopIcon;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
